# 
# update the films.sc spreadsheet when the films_to_ad.txt file changes
#


name: update films.sc with films_to_add.txt data

on:
  push:
    paths:
      - "films_to_add.txt"    # only triggered when this file changes

permissions:
  contents: write   # allows job to write .sc file back to repo

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install sc-im
        run: sudo apt-get update && sudo apt-get install -y sc-im

      - name: export films.sc to a csv file
        run: |
          # echo 'export "csv" "/tmp/films.csv"' > /tmp/export_cmd
          # use script to simulate terminal env on runner and get sc-im to run commands
          script -qec "sc-im --quite --quit_afterload --nocurses --export_csv films.sc > /tmp/films.csv" /dev/null

      - name: build sc-im commands
        run: |
           python3 - <<'EOF' > /tmp/script
           COLUMN_ID = "B"   # column that contains IDs
           COLUMN_TITLE = "C"   # column that containes titles
           ID_OFFSET = -2   # ID offset relative to row index

           # parse the spreadsheet data
           with open("/tmp/films.csv", "r") as f:
              lines = [l.strip() for l in f]

           # check for blank lines which affect id offset
           for line in lines:
              if not line:
                  ID_OFFSET += -1

           # index of row to start writing to
           next_row = len(lines)

           # parse titles to add
           with open("films_to_add.txt", "r") as f:
              titles = [t.strip() for t in f if t.strip()]

           # write commands
           for title in titles:
              cleaned_title = title.replace('"', '\\"')
              print(f'LABEL {COLUMN_ID}{next_row} = "{next_row + ID_OFFSET}"')
              print(f'LABEL {COLUMN_TITLE}{next_row} = "{cleaned_title}"')
              next_row += 1

           # print('EXECUTE "w! films.sc"')

           EOF

      - name: check commands
        run: cat /tmp/script

      - name: apply commands to sheet
        run: |
          # gets last byte of films.sc (tail -c1), strips new lines ("$(...)")  and checks if its non empty (-n)
          # if it is non empty (left side evaluaates to true) add a new line (echo)
          [ -n "$(tail -c1 films.sc)" ] && echo >> films.sc
          cat /tmp/script >> films.sc
          git diff films.sc

      - name: Commit updated spreadsheet
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add films.sc
          git diff --cached --quiet || git commit -m "Update films.sc from films_to_add.txt"
          git push

